// data.jsx — HallBook seed data

const VENUES = [
  {
    id: 'v1',
    name: 'The Atrium',
    district: 'Downtown · Riverside',
    capacity: 180,
    priceHour: 240,
    rating: 4.9,
    reviews: 312,
    tags: ['Wedding', 'Gala', 'Corporate'],
    available: 'now',
    nextGap: 'Free until 11pm tonight',
    coord: [38, 42],
    hero: 'warm',
    size: '4,200 sqft',
    ceiling: '18 ft',
    addons: ['Catering', 'AV Package', 'Floral'],
  },
  {
    id: 'v2',
    name: 'Loft 47',
    district: 'Arts District',
    capacity: 90,
    priceHour: 165,
    rating: 4.8,
    reviews: 204,
    tags: ['Birthday', 'Workshop'],
    available: 'soon',
    nextGap: 'Opens at 6:00 PM',
    coord: [62, 28],
    hero: 'cool',
    size: '2,100 sqft',
    ceiling: '14 ft',
    addons: ['Catering', 'DJ Booth'],
  },
  {
    id: 'v3',
    name: 'Garden Pavilion',
    district: 'North Park',
    capacity: 240,
    priceHour: 320,
    rating: 4.9,
    reviews: 488,
    tags: ['Wedding', 'Reception'],
    available: 'now',
    nextGap: 'Free 2h remaining',
    coord: [25, 68],
    hero: 'sage',
    size: '5,800 sqft',
    ceiling: 'Outdoor',
    addons: ['Catering', 'Tent', 'Heaters'],
  },
  {
    id: 'v4',
    name: 'The Forum',
    district: 'Midtown',
    capacity: 320,
    priceHour: 410,
    rating: 4.7,
    reviews: 176,
    tags: ['Corporate', 'Conference'],
    available: 'booked',
    nextGap: 'Next open Fri 8:00 AM',
    coord: [72, 58],
    hero: 'ink',
    size: '7,400 sqft',
    ceiling: '22 ft',
    addons: ['AV Package', 'Stage'],
  },
  {
    id: 'v5',
    name: 'Cedar Hall',
    district: 'Westside',
    capacity: 120,
    priceHour: 195,
    rating: 4.8,
    reviews: 267,
    tags: ['Birthday', 'Anniversary'],
    available: 'now',
    nextGap: 'Free until 2:00 AM',
    coord: [52, 76],
    hero: 'amber',
    size: '2,900 sqft',
    ceiling: '16 ft',
    addons: ['Catering', 'Photo Booth'],
  },
  {
    id: 'v6',
    name: 'Marble Room',
    district: 'Financial',
    capacity: 60,
    priceHour: 140,
    rating: 4.6,
    reviews: 98,
    tags: ['Meeting', 'Intimate'],
    available: 'soon',
    nextGap: 'Opens at 9:30 PM',
    coord: [82, 38],
    hero: 'stone',
    size: '1,400 sqft',
    ceiling: '12 ft',
    addons: ['AV Package'],
  },
];

const BOOKINGS = [
  {
    id: 'b1',
    venueId: 'v1',
    venue: 'The Atrium',
    date: 'Fri, Apr 24',
    dateISO: '2026-04-24',
    time: '6:00 PM – 11:00 PM',
    guests: 140,
    status: 'upcoming',
    pin: '4 8 2 9',
    confirm: 'HB-2A7F91',
    total: 1380,
    checkinOpens: 'Fri 5:30 PM',
  },
  {
    id: 'b2',
    venueId: 'v5',
    venue: 'Cedar Hall',
    date: 'Today, Apr 19',
    dateISO: '2026-04-19',
    time: '8:00 PM – 1:00 AM',
    guests: 85,
    status: 'active',
    pin: '6 3 1 7',
    confirm: 'HB-91C4D2',
    total: 1020,
    checkinOpens: 'Ready now',
  },
  {
    id: 'b3',
    venueId: 'v3',
    venue: 'Garden Pavilion',
    date: 'Sat, May 09',
    dateISO: '2026-05-09',
    time: '3:00 PM – 10:00 PM',
    guests: 210,
    status: 'upcoming',
    pin: '0 5 5 2',
    confirm: 'HB-66B1E8',
    total: 2340,
    checkinOpens: 'Sat 2:30 PM',
  },
  {
    id: 'b4',
    venueId: 'v2',
    venue: 'Loft 47',
    date: 'Sat, Mar 22',
    dateISO: '2026-03-22',
    time: '7:00 PM – 12:00 AM',
    guests: 60,
    status: 'completed',
    pin: '——',
    confirm: 'HB-4710CC',
    total: 825,
    checkinOpens: '',
  },
];

// 7-day hour grid for venue detail: 24h × 7d, values: 'open'|'booked'|'hold'
function buildSchedule(seed = 1) {
  const days = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];
  return days.map((d, di) => ({
    day: d,
    date: 19 + di,
    hours: Array.from({ length: 24 }, (_, h) => {
      const x = (di * 7 + h * 3 + seed) % 11;
      if (h < 8) return 'open';
      if (x === 0 || x === 3) return 'booked';
      if (x === 5) return 'hold';
      return 'open';
    }),
  }));
}

Object.assign(window, { VENUES, BOOKINGS, buildSchedule });
